name: Deploy on Raspberry Pi 

on: 
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PI_SSH_KNOWN_HOST_KEY }}" >> ~/.ssh/known_hosts
    - name: Deploy to Raspberry Pi on main branch push
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_PI_HOST_LIVEBOX_IP }}
        username: ${{ secrets.SSH_PI_USERNAME }}
        key: ${{ secrets.PI_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PI_PORT }}
        script: |
          cd /home/pi/Documents/react-music-sim
          git pull
          if docker ps | grep -q 'react-music-sim-web'; then
            docker compose restart
          else
            docker compose up -d
          fi